import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
    return (
        <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}> 
            <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
            <p style={{ fontSize: "18px", marginBottom: "30px" }}>
                This project was generated By{" "}
                <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
                    Dhiwise
                </a>
                . Quickly use below links to navigate through all pages.
            </p>
            <ul style={{ liststyle: "none", padding: "e" }}>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/paginaprincipal" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        PaginaPrincipal
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/iniciarsesion" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        IniciarSesion
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/observargastos" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        ObservarGastos
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/registrargastos" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        RegistrarGastos
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/recomendaciones" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Recomendaciones
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/crear cuenta" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        CrearCuenta
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/resumenmensual" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        ResumenMensual
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/olvidastecontrasena" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        OlvidasteContrasena
                    </Link>
                </li>
            </ul>
        </div>
    );
};
export default Home;