import { Img } from "./Img"; 
import { Text } from "./Text"; 
import { Heading } from "./Heading"; 
import { Button } from "./Button"; 
import { Input } from "./Input";
import { RadioGroup } from "./RadioGroup"; 
import { SelectBox } from "./SelectBox";
import { ReactTable } from "./ReactTable";
import { Radio } from "./Radio";
import { CheckBox } from "./CheckBox";
export { Img, Text, Heading, Button, Input, RadioGroup, SelectBox, ReactTable, Radio, CheckBox };